version: '3.7'
services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretpgpassword}
    ports:
      - '5432:5432'
  graphql-engine:
    image: hasura/graphql-engine:v2.31.0.ubuntu
    depends_on:
      - 'postgres'
    restart: always
    ports:
      - '8080:8080'
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD:-secretpgpassword}@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_LOG_LEVEL: debug
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_AUTH_HOOK: ${NODE_BASE_URL}/hasura/auth
      ACTIONS_BASE_URL: ${NODE_BASE_URL}/hasura/actions
      EVENTS_WEBHOOK_URL: ${NODE_BASE_URL}/hasura/events
      HASURA_GRAPHQL_CORS_DOMAIN: '*'
  minio:
    image: minio/minio:latest
    restart: always
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - ./data/minio:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server --console-address ":9090" /data